### ISSUE TITLE
Error: Cannot find module 'underscore'

### ISSUE THREAD

**Issue by woeterman94** [JohnMcLear/ep_inline_toolbar#2]
When installing this plugin I get:

`[2020-10-21 17:43:55.862] [ERROR] console - Failed to load 'ep_inline_toolbar/index' for 'ep_inline_toolbar/inline_toolbar/hooks/padInitToolbar': Error: Cannot find module 'underscore'`

Am I missing something?

Full log [here](https://gist.github.com/woeterman94/9a03b9134eca1c1da835c99d6d4fc1f4)

**Comment by JohnMcLear** [comment]
I just fixed the bugs, 0.1.0 should work.   https://github.com/JohnMcLear/ep_inline_toolbar/commits?author=JohnMcLear
